theme: jekyll-theme-minimal
title: My Personal Site
name: Davis Thrailkill
bio: Aspiring Data Scientist
twitter:
  username: d_thrailkill
linkedin:
  username: davis-thrailkill-bb262765
Description: A place for me to share my data science projects.
